# .streamlit/secrets.toml
[tmdb]
api_token = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZTNlMGVjMTI1ZDExYzc5ZTU1MjJiOWE2MWQ1MGY0MiIsIm5iZiI6MTc1MDc3MDc3Mi44OTIsInN1YiI6IjY4NWFhNDU0YWYyZWI4Y2U1OTIxY2FhOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.awg0kRMYXpK52TpJJRoI7DlPvew2UKBdYj6WsTQ1mfg"
